from app import db

class SurveyResponse(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    q1_time = db.Column(db.Integer)
    q1_closeness = db.Column(db.Integer)
    q2_time = db.Column(db.Integer)
    q2_closeness = db.Column(db.Integer)
    q3_time = db.Column(db.Integer)
    q3_closeness = db.Column(db.Integer)
    q4_time = db.Column(db.Integer)
    q4_closeness = db.Column(db.Integer)
    q5_time = db.Column(db.Integer)
    q5_closeness = db.Column(db.Integer)
    q6_time = db.Column(db.Integer)
    q6_closeness = db.Column(db.Integer)
    q7_time = db.Column(db.Integer)
    q7_closeness = db.Column(db.Integer)
    q8_time = db.Column(db.Integer)
    q8_closeness = db.Column(db.Integer)
    q9_time = db.Column(db.Integer)
    q9_closeness = db.Column(db.Integer)
    q10_time = db.Column(db.Integer)
    q10_closeness = db.Column(db.Integer)
    q11_time = db.Column(db.Integer)
    q11_closeness = db.Column(db.Integer)
    q12_time = db.Column(db.Integer)
    q12_closeness = db.Column(db.Integer)
    q13_time = db.Column(db.Integer)
    q13_closeness = db.Column(db.Integer)
    q14_time = db.Column(db.Integer)
    q14_closeness = db.Column(db.Integer)
    q15_time = db.Column(db.Integer)
    q15_closeness = db.Column(db.Integer)
    q16_time = db.Column(db.Integer)
    q16_closeness = db.Column(db.Integer)
    q17_time = db.Column(db.Integer)
    q17_closeness = db.Column(db.Integer)
    q18_time = db.Column(db.Integer)
    q18_closeness = db.Column(db.Integer)
    q19_time = db.Column(db.Integer)
    q19_closeness = db.Column(db.Integer)
    q20_time = db.Column(db.Integer)
    q20_closeness = db.Column(db.Integer)
